trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UseNode@2
    inputs:
      versionSpec: '24.x'
      checkLatest: true

  - script: npm ci
    displayName: 'Install NPM dependencies'

  - script: npx playwright install --with-deps
    displayName: 'Install Playwright Browsers'

  - script: npx cucumber-js
    displayName: 'Run Cucumber Tests'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(System.DefaultWorkingDirectory)/reports'
      artifactName: 'cucumber-reports'
      publishLocation: 'pipeline'
    condition: succeededOrFailed()

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(System.DefaultWorkingDirectory)/allure-results'
      artifactName: 'allure-results'
      publishLocation: 'pipeline'
    condition: succeededOrFailed()